version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "03:00"
    open-pull-requests-limit: 10
    version: 2
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
