version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "03:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
