name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --config=config/eleventy.config.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}